[configuration]
# NB! paths to files should be full paths to avoid errors
database = ..................../v33_koondkorpus_sentences_verb_pattern_obl_20241002-130310_test.db
sentences_db = ...................../v33_koondkorpus_sentences_sentences_20250220-130121.db
ner_timex_db = ..................../v33_ner_timex_20250922-094340.db
transaction_row_table = transaction_row
transaction_head_table = transaction_head
obl_table = spatial_obl
advmod_table = advmod
# Dirs for ekilex tag files
dir_obl_files =  ................./workflows/data/v05_wordlists_obl
dir_advmod_files =  ....................../workflows/data/v05_wordlists_advmod
# Data for n lines on graphs
confidence_values_table = confidence_values
confidence_range = 5000
# column to show morph-syntax errors
conflict_column = status
# column for ekilex+ner+timex tags 
tags_column = tags
# for graphs mainly, tags are comma separated
target_tag = ELT
other_tags = A,S
# where to save the graphs
dir_scatter_results = ....................../workflows/results/scatter
